apiVersion: v1
kind: Secret
metadata:
  name: hp-communication-secrets
  namespace: hp-communication
type: Opaque
stringData:
  db.username: hp_app_user
  db.password: CHANGE_ME
  api.key: your-api-key
  jwt.secret: your-jwt-secret
